name: CI

on: [push]

jobs:
  # This job will:
  #   * deploy a draft every time there is a commit that is not on master branch
  #   * comment on that commit with the deploy URL
  deployCommitDraft:
    name: Deploy draft to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref != 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # ... your other build steps to produce a build directory
      # e.g. `npm run build` for create-react-app

      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: fe1c856dbbd6c30a5b6fb7569ccc4e26ecb760c9
          netlify-auth-token: MpdKpXLccCFGkfal7atgcdKgP7eFmb67Jypx8QB6P8c
          netlify-site-id: 387eecf7-2ec4-4290-9e97-be290da12f33
          build-dir: './build'
          draft: true
          comment-on-commit: true

  # This job will:
  #   * deploy a production build every time there is a push only on the master branch
  #   * comment that commit with the deploy URL
  publishMasterCommit:
    name: Publish to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # ... your other build steps to produce a build directory
      # e.g. `npm run build` for create-react-app

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: fe1c856dbbd6c30a5b6fb7569ccc4e26ecb760c9
          netlify-auth-token: MpdKpXLccCFGkfal7atgcdKgP7eFmb67Jypx8QB6P8c
          netlify-site-id: 387eecf7-2ec4-4290-9e97-be290da12f33
          build-dir: './build'
          comment-on-commit: true
